FROM python:3
WORKDIR /tmp
COPY requirements.txt ./

RUN mkdir data && pip install -r requirements.txt
COPY data/cubes.json ./data/cubes.json
COPY populate_cubes_and_sets.py ./run.py

CMD ["python", "run.py"]