version: '3'
services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      PORT: 80
      ENV: "docker"
  redis:
    image: "redis:buster"
    command: redis-server --appendonly yes --appendfsync always
    ports:
      - 6379:6379
    volumes:
        - ./redis-data:/data